version: "3.7" 

networks:
        crawlernet:
                driver: bridge

services:
        eth2-crawler:
                image: "armiarma-eth2-crawler:latest"
                build:
                        context: .
                        dockerfile: Dockerfile
                networks:
                        crawlernet:
                ports: ["9020:9020/tcp", "9080:9080"]
                volumes: ["./peerstore:/armiarma/peerstore", "./config-files:/armiarma/config-files"]
                #restart: on-failure
                entrypoint: "/armiarma/armiarma-client --config-file=./config-files/config.json"
